version: '3.8'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: video_processing
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"

  video-processing-api:
    build:
      context: .
      dockerfile: VideoProcessingAPI/Dockerfile
    ports:
      - "5000:80"
  frontend:
    build:
      context: .
      dockerfile: video-processing-app/Dockerfile
    ports:
      - "4200:80"  # hoặc cổng mà bạn muốn expose cho ứng dụng Angular
    depends_on:
      - video-processing-api  # Nếu frontend phụ thuộc vào backend